/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BiciPalma;

import org.junit.Test;
import static org.junit.Assert.*;

public class BiciPalmaTest {
    @Test public void testSomeLibraryMethod() {
        BiciPalma classUnderTest = new BiciPalma();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
